package symbol;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int POW = 12;
  public static final int GE = 7;
  public static final int INTEGER = 33;
  public static final int INTEGER_CONST = 21;
  public static final int SEMI = 29;
  public static final int OUT = 39;
  public static final int MINUS = 4;
  public static final int WRITE = 42;
  public static final int WRITET = 44;
  public static final int NOT = 26;
  public static final int AND = 14;
  public static final int LT = 8;
  public static final int RPAR = 28;
  public static final int FUN = 38;
  public static final int OR = 15;
  public static final int BOOL = 36;
  public static final int COMMA = 30;
  public static final int DIV = 47;
  public static final int LOOP = 20;
  public static final int PLUS = 3;
  public static final int WRITELN = 43;
  public static final int MAIN = 40;
  public static final int ASSIGN = 2;
  public static final int IF = 16;
  public static final int ID = 50;
  public static final int LE = 9;
  public static final int WRITEB = 45;
  public static final int EOF = 0;
  public static final int RETURN = 49;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int DIVINT = 48;
  public static final int EQ = 10;
  public static final int OUTPAR = 46;
  public static final int REAL = 34;
  public static final int TIMES = 5;
  public static final int COLON = 31;
  public static final int ELSE = 18;
  public static final int READ = 41;
  public static final int WHILE = 19;
  public static final int STR_CONCAT = 13;
  public static final int REAL_CONST = 22;
  public static final int THEN = 17;
  public static final int NE = 11;
  public static final int END = 32;
  public static final int STRING = 35;
  public static final int LPAR = 27;
  public static final int FALSE = 25;
  public static final int STRING_CONST = 23;
  public static final int GT = 6;
  public static final int VAR = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "POW",
  "STR_CONCAT",
  "AND",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "LOOP",
  "INTEGER_CONST",
  "REAL_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE",
  "NOT",
  "LPAR",
  "RPAR",
  "SEMI",
  "COMMA",
  "COLON",
  "END",
  "INTEGER",
  "REAL",
  "STRING",
  "BOOL",
  "VAR",
  "FUN",
  "OUT",
  "MAIN",
  "READ",
  "WRITE",
  "WRITELN",
  "WRITET",
  "WRITEB",
  "OUTPAR",
  "DIV",
  "DIVINT",
  "RETURN",
  "ID"
  };
}

